dist: xenial
language: python
python:
- '3.7'
install:
- scripts/init-environment.sh
script:
- scripts/build.sh
- scripts/integration-test.sh

deploy:
- provider: gae
  keyfile: travis-deployer.json
  project: rss-aggregator-236707
  version: "$version"
  verbosity: debug
  skip_cleanup: true
  config: app.yaml
- provider: gae
  keyfile: travis-deployer.json
  project: rss-aggregator-236707
  version: "$version"
  config: cron.yaml

before_install:
- sudo apt-get update
- sudo apt-get install language-pack-nl
- openssl aes-256-cbc -K $encrypted_c4a98ea4d78f_key -iv $encrypted_c4a98ea4d78f_iv 
  -in secrets.tar.enc -out secrets.tar -d
- tar xf secrets.tar
- export version="develop-`git rev-parse --short HEAD`"
- echo $version
