version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      PORT: 8080
      ENVIRONMENT: LOCALHOST
      GOOGLE_APPLICATION_CREDENTIALS: secrets/google-appengine-credentials.json
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    command: ./scripts/start-python-in-dev-server.sh api.py

  cron:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      PORT: 8080
      ENVIRONMENT: LOCALHOST
      GOOGLE_APPLICATION_CREDENTIALS: secrets/google-appengine-credentials.json
    ports:
      - 8090:8080
    volumes:
      - .:/usr/src/app
    command: ./scripts/start-python-in-dev-server.sh cron.py

  frontend:
    build: frontend
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "cd /usr/src/app && cp src/Config.localhost.js src/Config.js && npm start"
