version: '3.3'

services:
  backend:
    build: .
    ports:
      - 5678:5678
    volumes:
      - .:/usr/src/app
    command: ["watchmedo", "auto-restart", "--recursive", "--pattern=*.py", "--directory=.", "--", "python3", "-m", "ptvsd", "--host", "0.0.0.0", "--port", "5678", "main.py"]

  frontend:
    build: .
    volumes:
      - .:/usr/src/app
    command: sh -c "cd frontend && npm start"

  proxy:
    build: nginx-dev-proxy
    ports: 
      - 80:80

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
