version: 2.1
jobs:
    build:
        machine:
            image: ubuntu-1604:201903-01
        steps:
            - checkout
            - run:
                name: decrypt test connection
                command: scripts/decrypt-google-appengine-credentials.sh
            - run:
                name: build docker image
                command: scripts/build-docker-image.sh
            - run:
                name: verify the build
                command: docker run -v `pwd`:/usr/src/app rss-aggregator-app scripts/build.sh
            - run:
                name: integration tests
                command: docker-compose -f integration-test-dc.yml up --build --exit-code-from integration_test integration_test
            - store_artifacts:
                path: build-reports/html
                destination: test-reports
