name: Run tests
on: [push]

jobs:
  build:
    name: make-docker-image-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Decrypt the secret for google-app-engine
        run: scripts/decrypt-google-appengine-credentials.sh
        env:
          GOOGLE_APP_ENGINE_KEY: ${{ secrets.GOOGLE_APP_ENGINE_KEY }}
      - name: Build the python docker image
        run: scripts/build-docker-image.sh
      - name: Verify the build
        run: docker run -v `pwd`:/usr/src/app rss-aggregator-app scripts/build.sh
